name: clarity
description: Odoo JSON RPC Connector library for Flutter allows you to connect with Odoo 12+. Authenticate, Read data, updating and creating data, JSON type controllers, custom model methods
version: 0.0.2
homepage: https://www.github.com/netesy/clarity

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


platforms:
  android:
  ios:
  linux:
  macos:
  windows:
